services:
  postgres:
    image: postgres:16-alpine
    container_name: examen_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: examen_microservicios
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend_tecnico:
    build: ./backend_tecnico
    container_name: backend_tecnico
    restart: always
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: examen_microservicios
    depends_on:
      - postgres

  backend_servicio:
    build: ./backend_servicio
    container_name: backend_servicio
    restart: always
    ports:
      - "3002:3002"
    environment:
      PORT: 3002
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: examen_microservicios
    depends_on:
      - postgres

  backend_dispositivo:
    build: ./backend_dispositivo
    container_name: backend_dispositivo
    restart: always
    ports:
      - "3003:3003"
    environment:
      PORT: 3003
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: examen_microservicios
    depends_on:
      - postgres

  frontend_tecnico:
    build: ./frontend_tecnico
    container_name: frontend_tecnico
    restart: always
    ports:
      - "5171:5171"
    volumes:
      - ./frontend_tecnico:/app:delegated
      - frontend_tecnico_node_modules:/app/node_modules
    depends_on:
      - backend_tecnico

  frontend_servicio:
    build: ./frontend_servicio
    container_name: frontend_servicio
    restart: always
    ports:
      - "5172:5172"
    volumes:
      - ./frontend_servicio:/app:delegated
      - frontend_servicio_node_modules:/app/node_modules
    depends_on:
      - backend_servicio

  frontend_dispositivo:
    build: ./frontend_dispositivo
    container_name: frontend_dispositivo
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./frontend_dispositivo:/app:delegated
      - frontend_dispositivo_node_modules:/app/node_modules
    depends_on:
      - backend_dispositivo

volumes:
  postgres_data:
  frontend_tecnico_node_modules:
  frontend_servicio_node_modules:
  frontend_dispositivo_node_modules:
